### ISSUE TITLE
docs: Improve the `README.md`

### ISSUE THREAD

**Issue by 0xMukesh** [byteslash-hub/bytoid#7]
Improve the README.md file by adding using/developer guide

The developer guide should contain the following steps:
- Creating a bot account on discord dev portal
- Creating a MongoDB database
- Creating a `.env` file and storing the environment variables
- Installing the dependencies (`npm install`)
- Starting the bot (`npm run dev`)

**Comment by Hat52** [comment]
Hello, I would like to take up this issue.

**Comment by 0xMukesh** [comment]
@Hat52 Alright. I'll assign you to this issue
