### ISSUE TITLE
docs: Create issue and pull request templates

### ISSUE THREAD

**Issue by 0xMukesh** [byteslash-hub/bytoid#8]
Here are the documentation on how to create issue templates

- Issue templates: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-templates
- Pull request templates: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

**Comment by vaishnav-sh** [comment]
Hey! I would like to work on this.

**Comment by 0xMukesh** [comment]
@vaishnav-sh Alright. I'll assign the issue to you
